#!/usr/bin/env php
<?php
/**
 * console
 */
require __DIR__ . "/vendor/autoload.php";

$console = new Comnect\Console\Console;
$container = $console->getContainer();
// container, dependency injections
require __DIR__ . "/bootstrap/dependencies.php";

$console->boot();