#!/usr/bin/env php
<?php
require __DIR__ . "/vendor/autoload.php";
// user functions
require __DIR__ . "/bootstrap/autoload.php";
// container, dependency injections
require __DIR__ . "/bootstrap/global.php";

$console = new Comnect\Console\Console($app);
$console->boot();